// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async sessionList() : Promise<Result<SessionListDto, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configGet() : Promise<Result<ConfigDto, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionSpawn(projectId: string, sessionId: string, agent: string | null, base: string | null, workspace: WorkspaceModeDto | null, branch: string | null, worktreeRoot: string | null, onOutput: TAURI_CHANNEL<BridgeOutput>) : Promise<Result<ChannelHandle, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_spawn", { projectId, sessionId, agent, base, workspace, branch, worktreeRoot, onOutput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionAttach(projectId: string, sessionId: string, onOutput: TAURI_CHANNEL<BridgeOutput>) : Promise<Result<ChannelHandle, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_attach", { projectId, sessionId, onOutput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionRespawn(projectId: string, sessionId: string, agent: string | null, onOutput: TAURI_CHANNEL<BridgeOutput>) : Promise<Result<ChannelHandle, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_respawn", { projectId, sessionId, agent, onOutput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionStop(projectId: string, sessionId: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_stop", { projectId, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionRemove(projectId: string, sessionId: string, force: boolean) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_remove", { projectId, sessionId, force }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionWrite(handle: ChannelHandle, bytes: number[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_write", { handle, bytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionResize(handle: ChannelHandle, rows: number, cols: number) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_resize", { handle, rows, cols }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionClose(handle: ChannelHandle) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_close", { handle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configGetEditable() : Promise<Result<EditableConfigDto, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_get_editable") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configInsertHost(id: string, input: HostInputDto) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_insert_host", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configUpdateHost(id: string, input: HostInputDto) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_update_host", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configRemoveHost(id: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_remove_host", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configInsertProject(id: string, input: ProjectInputDto) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_insert_project", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configUpdateProject(id: string, input: ProjectInputDto) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_update_project", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configRemoveProject(id: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_remove_project", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configInsertAgent(id: string, input: AgentInputDto) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_insert_agent", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configUpdateAgent(id: string, input: AgentInputDto) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_update_agent", { id, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configRemoveAgent(id: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_remove_agent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async externalTerminals() : Promise<Result<DetectedTerminalDto[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("external_terminals") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openExternalTerminal(projectId: string, sessionId: string, terminalId: string | null) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_external_terminal", { projectId, sessionId, terminalId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyAttachCommand(projectId: string, sessionId: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_attach_command", { projectId, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configSetTerminal(terminalId: string | null) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_set_terminal", { terminalId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open (or replace) this device's pairing window; returns the QR code + TTL.
 */
async pairingOpenWindow(ttlSecs: number | null) : Promise<Result<PairingCodeDto, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pairing_open_window", { ttlSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Confirm the arrived device's fingerprint (enrol it).
 */
async pairingConfirm(deviceId: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pairing_confirm", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reject the arrived device (grant nothing durable).
 */
async pairingReject(deviceId: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pairing_reject", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close the current pairing window without pairing anyone.
 */
async pairingCancel() : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pairing_cancel") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List this bridge's paired devices (live roster).
 */
async listDevices() : Promise<Result<DeviceInfoDto[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Un-pair a device (drop from roster, kick any live session).
 */
async revokeDevice(deviceId: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revoke_device", { deviceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * This bridge's own identity fingerprint (ADR-0021 D5), for the pairing UI.
 */
async bridgeFingerprint() : Promise<Result<string, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("bridge_fingerprint") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openInVscode(projectId: string, sessionId: string) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_vscode", { projectId, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
configChanged: ConfigChanged,
pairingDeviceArrived: PairingDeviceArrived,
pairingResult: PairingResult,
pairingWindowOpened: PairingWindowOpened,
rosterChanged: RosterChanged
}>({
configChanged: "config-changed",
pairingDeviceArrived: "pairing-device-arrived",
pairingResult: "pairing-result",
pairingWindowOpened: "pairing-window-opened",
rosterChanged: "roster-changed"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * A configured agent, id-only. The launch `command` argv is a launch detail
 * (not a label) and is intentionally omitted — the new-session dialog needs
 * only the id to pass as `SpawnSpec::agent`.
 */
export type AgentDto = { id: string }
/**
 * Form payload for create/edit of an agent.
 */
export type AgentInputDto = { command: string[]; 
/**
 * Preserved across the editor round-trip so that a TOML-set `provision`
 * file is not silently dropped when the user edits an unrelated field.
 */
provision?: ProvisionFileDto | null }
export type BridgeError = { kind: "sessionExists"; message: string } | { kind: "sessionNotFound"; message: string } | { kind: "channelClosed" } | { kind: "transport"; message: string } | { kind: "plan"; message: string } | { kind: "invalidId"; message: string } | { kind: "unknownHandle" } | { kind: "invalidSize"; message: string } | 
/**
 * The config file exists but could not be read or parsed. A *missing*
 * file is NOT this error — it maps to an empty config (a fresh device is
 * valid). Permission/parse/validation failures surface here so the sidebar
 * shows a banner instead of a silently-empty tree.
 */
{ kind: "config"; message: string } | 
/**
 * An in-app config edit (insert/update/remove) was rejected: a duplicate
 * id, a missing id, a dangling reference, a referenced entry being removed,
 * or a save IO failure. Carries the rendered (already sanitized)
 * `ConfigError`. Distinct from `Config` (whole-file load failure → sidebar
 * banner) so the frontend can show this inline on the offending form.
 */
{ kind: "configEdit"; message: string } | 
/**
 * External-terminal launch could not resolve a terminal: nothing
 * configured (zero or several detected), or the config names an unknown
 * or uninstalled registry id. The frontend deep-links Settings on this
 * kind (spec §4); launch/exec failures are `Transport` instead.
 */
{ kind: "terminalNotConfigured"; message: string } | 
/**
 * A session removal was blocked because the workspace has unsaved state
 * (uncommitted changes or commits not pushed to any remote). Carry the
 * reason so the frontend can show a targeted warning and offer `force`.
 */
{ kind: "workspaceDirty"; message: string; reason: DirtyReasonDto } | 
/**
 * A relay/pairing command was invoked but this device hosts no relay bridge
 * (no `[relay]` section — or it was removed by a live config edit, #277 —
 * so the supervisor holds no `PairingHandles`). The UI shows a "relay not
 * configured" state instead of a pairing panel.
 */
{ kind: "relayNotConfigured"; message: string } | 
/**
 * A relay/pairing or roster operation failed inside the running bridge
 * (e.g. the relay link was down when opening a window, or roster storage
 * errored on revoke). Distinct from `RelayNotConfigured` (no bridge at all).
 */
{ kind: "relay"; message: string }
/**
 * Streamed from a session's PTY to the frontend. Internally tagged + camelCase
 * so the generated TS is a clean discriminated union. A local bridge<->frontend
 * DTO (NOT a wire-protocol type), so it is free to grow.
 */
export type BridgeOutput = { event: "bytes"; bytes: number[] } | { event: "closed" } | { event: "statusChange"; status: SessionStatusDto } | { event: "previewUpdate"; preview: string } | 
/**
 * The activity-hook pipeline is confirmed wired for this session (#198):
 * core parsed its first OSC-7366 marker this attach. Presence is the signal.
 */
{ event: "markerSeen" }
/**
 * Opaque handle the frontend uses to address one open channel (write/resize/close).
 */
export type ChannelHandle = number
/**
 * Emitted when the per-device config file changes on disk (file watcher).
 * Carries no payload — the frontend re-reads via `config_get` (its existing
 * refresh path), so the event is a ping, not a config snapshot.
 */
export type ConfigChanged = null
/**
 * The whole per-device config, projected for the sidebar. `Default` is the
 * empty config a fresh device (no file yet) renders.
 */
export type ConfigDto = { hosts: HostDto[]; projects: ProjectDto[]; agents: AgentDto[]; terminal: TerminalPreferenceDto | null }
/**
 * A detected terminal, id + display name only.
 */
export type DetectedTerminalDto = { id: string; name: string }
/**
 * One paired device, for the roster view. `device_id` is the 64-hex string;
 * `fingerprint` is the short human-comparable form (ADR-0021 D5) of the
 * device's pinned static key.
 */
export type DeviceInfoDto = { deviceId: string; name: string; fingerprint: string; enrolledAt: number | null; lastConnectedAt: number | null }
export type DirtyReasonDto = "uncommitted" | "notOnRemote" | "both"
/**
 * The editable config plus its validation state (ADR-0006 degraded mode).
 * 
 * In the normal case `config` is `Some` and `issues` is empty. When the base
 * file is *semantically* invalid, `config` is `None` (no typed config can be
 * produced), `issues` lists what is broken (rendered + sanitized), and
 * `present` lists the entry ids still in the file so the UI can offer
 * per-entity delete recovery without the whole document having to validate
 * first. A file that isn't even parseable surfaces as a `Config` load error,
 * not a degraded document.
 */
export type EditableConfigDto = { config: EditorConfigDto | null; issues: string[]; present: PresentEntitiesDto }
/**
 * An agent with its full launch argv (the display `AgentDto` carries only id).
 */
export type EditorAgentDto = { id: string; command: string[]; provision: ProvisionFileDto | null }
/**
 * The whole per-device config, projected **un-redacted** for the editor forms.
 */
export type EditorConfigDto = { hosts: EditorHostDto[]; projects: EditorProjectDto[]; agents: EditorAgentDto[] }
/**
 * A host with its full connection details (the editable form state).
 */
export type EditorHostDto = { id: string; name: string | null; transport: TransportDto; worktreeRoot: string | null }
/**
 * A project with every editable field, including the on-host `path` and
 * `workspace` mode that the display `ProjectDto` omits.
 */
export type EditorProjectDto = { id: string; name: string | null; hostId: string; path: string; workspace: WorkspaceModeDto; agent: string; base: string | null; worktreeRoot: string | null }
/**
 * A configured host, label-only. The `transport` discriminant is all the UI
 * needs (an icon/badge); the connection details never cross.
 */
export type HostDto = { id: string; name: string | null; transport: TransportKindDto }
/**
 * Form payload for create/edit of a host. The entry id is a separate command
 * argument, so it is not carried here.
 */
export type HostInputDto = { name: string | null; transport: TransportDto; 
/**
 * Preserved across the editor round-trip so that a TOML-set `worktree_root`
 * is not silently cleared when the user edits an unrelated field. B2 will
 * add the form input; here we just thread the value through so the save
 * path does not destroy it.
 */
worktreeRoot?: string | null }
/**
 * One host's discovery outcome for a single `Bridge::list` poll. `available`
 * is false when the host's `source.list()` errored (then `sessions` is empty);
 * retention of last-good rows for a transiently-down host is the frontend's job.
 */
export type HostSessionsDto = { hostId: string; available: boolean; sessions: SessionMetaDto[] }
/**
 * A kubectl connection field for the editor: `command = false` is a literal
 * value, `command = true` means `value` is a shell command line resolved at
 * connect time. Flat + form-friendly for the TS toggle.
 */
export type KubectlFieldDto = { command: boolean; value: string }
/**
 * A freshly minted pairing code for the UI: the encoded string to render as a
 * QR (and offer as a copyable fallback), plus the window deadline for a
 * countdown. `code` embeds the PSK by design (ADR-0021 D1); never log it —
 * and the manual [`Debug`] impl redacts it so a `{:?}` cannot either (#278).
 */
export type PairingCodeDto = { 
/**
 * The `remora-pair:1:…` string (QR payload + copyable fallback).
 */
code: string; 
/**
 * Unix seconds the window (and this code) expire — drives the countdown.
 */
expiresAt: number; 
/**
 * The window lifetime, in seconds, it was opened for.
 */
ttlSecs: number }
/**
 * A device reached the open window and awaits the user's confirm/reject; the
 * UI shows `fingerprint` for the human to compare against the device's screen.
 */
export type PairingDeviceArrived = { deviceId: string; name: string; fingerprint: string }
/**
 * The terminal outcome of one pairing attempt (ADR-0021).
 */
export type PairingOutcomeDto = { kind: "paired"; deviceId: string; name: string } | { kind: "rejected"; deviceId: string } | { kind: "expired" }
/**
 * A pairing attempt reached a terminal state.
 */
export type PairingResult = { outcome: PairingOutcomeDto }
/**
 * A pairing window opened; the UI shows `code` until `expires_at` (Unix
 * seconds). `code` embeds the PSK by design (ADR-0021 D1); never log it.
 */
export type PairingWindowOpened = { code: string; expiresAt: number }
/**
 * Entry ids present in each section of the document, regardless of validity —
 * the delete targets degraded-mode recovery offers. Mirrors core's
 * [`PresentIds`] field-for-field; the `From` impl below is the single place to
 * update if either gains a section, so keep the two in lockstep.
 */
export type PresentEntitiesDto = { hosts: string[]; projects: string[]; agents: string[] }
/**
 * A configured project: its label, the host it lives on, its workspace mode,
 * and its default agent. The on-host `path` is intentionally omitted — it is
 * not needed to render the tree and is closer to a connection detail than a
 * label. Workspace mode is structural (it affects session UI), not a secret.
 */
export type ProjectDto = { id: string; name: string | null; hostId: string; workspace: WorkspaceModeDto; agent: string }
/**
 * Form payload for create/edit of a project. `host_id` and `agent` are
 * references to existing entries; converting parses them into ids.
 */
export type ProjectInputDto = { name: string | null; hostId: string; path: string; workspace: WorkspaceModeDto; agent: string; base?: string | null; 
/**
 * Preserved across the editor round-trip so that a TOML-set `worktree_root`
 * is not silently cleared when the user edits an unrelated field. B2 will
 * add the form input; here we just thread the value through so the save
 * path does not destroy it.
 */
worktreeRoot?: string | null }
/**
 * A single provisioned file (ADR-0003 data, #196): the editor's counterpart
 * to core's `ProvisionFile`. Shared by the read projection and the write
 * inputs so the form round-trips exactly what is on disk.
 */
export type ProvisionFileDto = { path: string; content: string; mode: number | null }
/**
 * The roster changed (a device enrolled or was revoked); the UI re-queries
 * `list_devices`. No payload — a ping, like [`super::commands::ConfigChanged`].
 */
export type RosterChanged = null
/**
 * Result of a discovery poll: one bucket per host attempted this poll, in
 * config order. Sessions are sorted by (project_id, session_id) within each
 * bucket (the frontend re-sorts after flattening across hosts).
 */
export type SessionListDto = { hosts: HostSessionsDto[] }
export type SessionMetaDto = { projectId: string; sessionId: string; state: SessionStateDto; 
/**
 * Agent id the sandbox advertises for this session. Untrusted,
 * display-only: the discovery layer sanitizes it; never build a command
 * or path from it.
 */
agent: string | null; createdAt: number | null; 
/**
 * Workspace path the sandbox advertises. Untrusted, display-only (same
 * rule as `agent`).
 */
workspacePath: string | null; 
/**
 * Effective workspace mode discovered for this session (real state), or
 * null from an older sender. Drives sidebar/tab gating.
 */
workspace: WorkspaceModeDto | null; 
/**
 * Git branch the sandbox advertises for this session. Untrusted,
 * display-only (same rule as `agent`/`workspace_path`).
 */
branch: string | null }
export type SessionStateDto = "live" | "stopped"
/**
 * Frontend-facing mirror of `remora_protocol::SessionStatus` (which is
 * specta-agnostic). A local DTO keeps the protocol crate dependency-light while
 * giving the generated TS a clean string union. snake_case matches the
 * frontend `ActivityState` tokens ("working" | "idle" | "awaiting" | "unknown").
 */
export type SessionStatusDto = "working" | "idle" | "awaiting" | "unknown"
/**
 * The user's external-terminal preference, projected as-is. NOT a connection
 * secret: the registry id is a label; the custom argv is the user's own
 * LOCAL launcher command (same trust class as an agent launch argv, but —
 * unlike `AgentDto` — the UI needs the value itself to render the read-only
 * "Custom (config file)" state and the menu label).
 */
export type TerminalPreferenceDto = string | string[]
/**
 * Transport + connection details, shared by the read projection and the write
 * inputs (it round-trips: what the form shows is what it submits). Internally
 * tagged on `kind` so the TS side discriminates on a single field.
 */
export type TransportDto = { kind: "ssh"; host: string; user: string | null; port: number | null } | { kind: "kubectl"; pod: KubectlFieldDto; namespace: KubectlFieldDto | null; context: KubectlFieldDto | null; container: KubectlFieldDto | null }
/**
 * Which transport a host uses — the discriminant only, no connection fields.
 */
export type TransportKindDto = "ssh" | "kubectl"
/**
 * Workspace mode, shared by the read projection and the write inputs.
 */
export type WorkspaceModeDto = "worktree" | "shared"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
