// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async sessionList() : Promise<Result<SessionMetaDto[], BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configGet() : Promise<Result<ConfigDto, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("config_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionSpawn(projectId: string, sessionId: string, agent: string | null, onOutput: TAURI_CHANNEL<BridgeOutput>) : Promise<Result<ChannelHandle, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_spawn", { projectId, sessionId, agent, onOutput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionAttach(projectId: string, sessionId: string, onOutput: TAURI_CHANNEL<BridgeOutput>) : Promise<Result<ChannelHandle, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_attach", { projectId, sessionId, onOutput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionRespawn(projectId: string, sessionId: string, agent: string | null, onOutput: TAURI_CHANNEL<BridgeOutput>) : Promise<Result<ChannelHandle, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_respawn", { projectId, sessionId, agent, onOutput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionWrite(handle: ChannelHandle, bytes: number[]) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_write", { handle, bytes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionResize(handle: ChannelHandle, rows: number, cols: number) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_resize", { handle, rows, cols }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sessionClose(handle: ChannelHandle) : Promise<Result<null, BridgeError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("session_close", { handle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type BridgeError = { kind: "sessionExists"; message: string } | { kind: "sessionNotFound"; message: string } | { kind: "channelClosed" } | { kind: "transport"; message: string } | { kind: "plan"; message: string } | { kind: "invalidId"; message: string } | { kind: "unknownHandle" } | { kind: "invalidSize"; message: string } | 
/**
 * The config file exists but could not be read or parsed. A *missing*
 * file is NOT this error — it maps to an empty config (a fresh device is
 * valid). Permission/parse/validation failures surface here so the sidebar
 * shows a banner instead of a silently-empty tree.
 */
{ kind: "config"; message: string }
/**
 * Streamed from a session's PTY to the frontend. Internally tagged + camelCase
 * so the generated TS is a clean discriminated union. A local bridge<->frontend
 * DTO (NOT a wire-protocol type), so it is free to grow.
 */
export type BridgeOutput = { event: "bytes"; bytes: number[] } | { event: "closed" }
/**
 * Opaque handle the frontend uses to address one open channel (write/resize/close).
 */
export type ChannelHandle = number
/**
 * The whole per-device config, projected for the sidebar. `Default` is the
 * empty config a fresh device (no file yet) renders.
 */
export type ConfigDto = { hosts: HostDto[]; projects: ProjectDto[] }
/**
 * A configured host, label-only. The `transport` discriminant is all the UI
 * needs (an icon/badge); the connection details never cross.
 */
export type HostDto = { id: string; name: string | null; transport: TransportKindDto }
/**
 * A configured project: its label, the host it lives on, and its default
 * agent. The on-host `path` is intentionally omitted — it is not needed to
 * render the tree and is closer to a connection detail than a label.
 */
export type ProjectDto = { id: string; name: string | null; hostId: string; agent: string }
export type SessionMetaDto = { projectId: string; sessionId: string; state: SessionStateDto; 
/**
 * Agent id the sandbox advertises for this session. Untrusted,
 * display-only: the discovery layer sanitizes it; never build a command
 * or path from it.
 */
agent: string | null; createdAt: number | null; 
/**
 * Workspace path the sandbox advertises. Untrusted, display-only (same
 * rule as `agent`).
 */
workspacePath: string | null }
export type SessionStateDto = "live" | "stopped"
/**
 * Which transport a host uses — the discriminant only, no connection fields.
 */
export type TransportKindDto = "ssh" | "kubectl"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
